services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./centinela_logs:/centinela_logs
      - .:/app
    restart: always
    ports:
      - "8001:8001"
    environment:
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_HOST=${NEO4J_HOST}
      - NEO4J_PORT=${NEO4J_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - ADMIN_CENTINELA=${ADMIN_CENTINELA}
      - PASSWORD_CENTINELA=${PASSWORD_CENTINELA}
    depends_on:
      - mongo
      - neo4j
    links:
      - "neo4j:neo4j"
      - "mongo:mongo"

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    volumes:
      - ./mongo_db/data:/data/db

networks:
  default:
    driver: bridge
