from typing import Any, Dict, List, Protocol


class ScopusRepositoryPort(Protocol):
    def iter_raw_articles(self): ...
    def iter_silver_articles(self): ...


class GoldDatasetRepositoryPort(Protocol):
    def iter_gold_ml_features(self): ...


class GraphPublisherPort(Protocol):
    def publish(self, graph_entities: List[Dict[str, Any]]) -> Dict[str, Any]: ...


class MLModelsPort(Protocol):
    def vectorize(self, text: str, translate_to_english: bool = True, clean_text: bool = True) -> Dict[str, Any]: ...
    def keywords(self, text: str, top_n: int = 10) -> Dict[str, Any]: ...
    def build_tfidf(self, documents: List[Dict[str, Any]], version: str = "v10.0") -> Dict[str, Any]: ...
    def search_tfidf(self, query: str, version: str = "v10.0", top_k: int = 10) -> Dict[str, Any]: ...
